"""Added phone number to users table.

Revision ID: a5372cd0153f
Revises: edf05138e08b
Create Date: 2022-04-06 12:24:37.291649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5372cd0153f'
down_revision = 'edf05138e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
